nelmio_api_doc:
    documentation:
        info:
            title: Bilemo
            description:
            version: 1.0.0
        components:
            parameters:
                Filtre:
                    name: filter
                    in: query
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Authorization: Bearer {jwt}'
                    name: Authorization
                    in: header
        security:
            -   Bearer: [ ]
    #            schemas:
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

